### ISSUE TITLE
add this form link to the Security Issues reporting method

### ISSUE THREAD

**Issue by devopstoday11** [intelops/tarian-detector#25]
@AnamikaSanjay @c-ravela 

https://intelops.ai/opensource-security-reporting-form/ 

Made this form to collect the security issues details for all the projects. Use this above [link](https://intelops.ai/opensource-security-reporting-form/)  in the project(s) documentation so that the security engineers or bug bounty hunters or ethical hacker or contributors can report us the security issues using this Form. 

I was going to add it myself, but I didn't find the place where to add it, in which file. 
Maybe I missed checking the right file.

**Comment by AnamikaSanjay** [comment]
commit : 7055b744fa17f85834151154e594bdc674152b2d 
added security form to the security disclosure
